<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.4.0</version>
	</parent>
	<groupId>com.oxyl</groupId>
	<artifactId>technight-api-first</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>technight-api-first</name>
	<description>Demo project for API First</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>23</java.version>

		<openapi-generator-maven-plugin.version>7.7.0</openapi-generator-maven-plugin.version>

		<javax-annotation-api.version>1.3.2</javax-annotation-api.version>
		<jackson-databind-nullable.version>0.2.6</jackson-databind-nullable.version>

		<openfeign.version>12.4</openfeign.version>
		<openfeign-form.version>3.8.0</openfeign-form.version>
		<findbugs.jsr305-version>3.0.2</findbugs.jsr305-version>

		<javax-servlet-api.version>4.0.1</javax-servlet-api.version>
		<swagger-core-v3.version>2.2.14</swagger-core-v3.version>
		<jakarta-validation-version>3.0.2</jakarta-validation-version>
	</properties>
	<dependencies>
		<!--- Spring Boot -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-undertow</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<!--- OpenFeign -->
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-core</artifactId>
			<version>${openfeign.version}</version>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-okhttp</artifactId>
			<version>${openfeign.version}</version>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-jackson</artifactId>
			<version>${openfeign.version}</version>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-slf4j</artifactId>
			<version>${openfeign.version}</version>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign.form</groupId>
			<artifactId>feign-form</artifactId>
			<version>${openfeign-form.version}</version>
		</dependency>
		<!-- Jackson -->
		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
			<version>${jackson-databind-nullable.version}</version>
		</dependency>
		<!-- Annotations -->
		<dependency>
			<groupId>com.google.code.findbugs</groupId>
			<artifactId>jsr305</artifactId>
			<version>${findbugs.jsr305-version}</version>
		</dependency>
		<dependency>
			<groupId>javax.annotation</groupId>
			<artifactId>javax.annotation-api</artifactId>
			<version>${javax-annotation-api.version}</version>
		</dependency>

		<!-- Server -->
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>${javax-servlet-api.version}</version>
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>${swagger-core-v3.version}</version>
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-models</artifactId>
			<version>${swagger-core-v3.version}</version>
		</dependency>
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
			<version>${jakarta-validation.version}</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<!-- Generator Java -->
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>${openapi-generator-maven-plugin.version}</version>
				<configuration>
					<output>${project.build.directory}/generated-sources</output>
					<importMappings>
						<importMapping>JsonNode=com.fasterxml.jackson.databind.JsonNode</importMapping>
						<importMapping>Object=java.lang.Object</importMapping>
						<importMapping>Date=java.time.LocalDate</importMapping>
					</importMappings>
					<typeMappings>
						<typeMapping>Double=java.math.BigDecimal</typeMapping>
						<typeMapping>object+JSonNode=JsonNode</typeMapping>
						<typeMapping>Date=LocalDate</typeMapping>
					</typeMappings>
					<generateApiTests>false</generateApiTests>
					<generateModelTests>false</generateModelTests>
					<skipIfSpecIsUnchanged>true</skipIfSpecIsUnchanged>
					<skipValidateSpec>true</skipValidateSpec>
					<configOptions>
						<implicitHeaders>true</implicitHeaders>
						<useBeanValidation>false</useBeanValidation>
						<skipDefaultInterface>true</skipDefaultInterface>
						<sourceFolder>src/main/java</sourceFolder>
						<interfaceOnly>true</interfaceOnly>
						<dateLibrary>java8</dateLibrary>
						<serializableModel>true</serializableModel>
						<useSpringBoot3>false</useSpringBoot3>
						<useJakartaEe>true</useJakartaEe>
						<useTags>true</useTags>
					</configOptions>
				</configuration>
				<executions>
					<execution>
						<id>generate-sources-themealdb</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/spec/themealdb.yml</inputSpec>
							<generatorName>java</generatorName>
							<output>${project.build.directory}/generated-sources</output>
							<apiPackage>com.oxyl.technight_api_first.themealdb.api</apiPackage>
							<modelPackage>com.oxyl.technight_api_first.themealdb.model</modelPackage>
							<invokerPackage>com.oxyl.technight_api_first.themealdb.client</invokerPackage>
							<library>feign</library>
						</configuration>
					</execution>
					<execution>
						<id>generate-sources-server</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/spec/api.yml</inputSpec>
							<generatorName>spring</generatorName>
							<modelNameSuffix>Dto</modelNameSuffix>
							<output>${project.build.directory}/generated-sources</output>
							<apiPackage>com.oxyl.technight_api_first.server.api</apiPackage>
							<modelPackage>com.oxyl.technight_api_first.server.model</modelPackage>
							<invokerPackage>com.oxyl.technight_api_first.server.client</invokerPackage>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
