openapi: 3.0.1
info:
  title: Swagger Technight Api First
  description: |-
    Api qui permets de récupérer des données depuis l'API TheMealDB
  contact:
    email: fguibon@oxyl.fr
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080
tags:
  - name: Meals
    description: Search meals
paths:
  /meals:
    get:
      tags:
        - Meals
      summary: Search for meals by ingredient, category or area
      operationId: getMeals
      parameters:
        - name: ingredient
          in: query
          description: Main ingredient name
          required: false
          schema:
            type: string
        - name: category
          in: query
          description: Category
          required: false
          schema:
            type: string
        - name: area
          in: query
          description: Area
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MealList'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          example: "Invalid parameters"
    Meal:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Katsu Chicken curry"
        thumbnail:
          type: string
          example: "https://www.themealdb.com/images/media/meals/vwrpps1503068729.jpg"
    MealList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Meal'